# This is a config for E2B sandbox template.
# You can use template ID (tbaq0p4sour8onsxcks9) or template name (vibe-nextjs-hha297) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-hha297") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-hha297") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-hha297')

team_id = "01dc105a-4348-45d9-9a11-7322a5f1fc66"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-hha297"
template_id = "tbaq0p4sour8onsxcks9"
